version: '2.4'

services:
  backend:
    build:
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/backend/src
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_DATABASE=neo4j
      - GRAPHQL_SERVER_PORT=${GRAPHQL_SERVER_PORT}
      - GRAPHQL_SERVER_PATH=${GRAPHQL_SERVER_PATH}
      - GRAPHQL_SERVER_HOST=${GRAPHQL_SERVER_HOST}
    ports:
      - ${GRAPHQL_SERVER_PORT}:${GRAPHQL_SERVER_PORT}

  neo4j:
    image: neo4j:4.3.3
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_dbms_security_auth__enabled: "false"
      NEO4J_dbms_allow__upgrade: "true"
      NEO4JLABS_PLUGINS: "[\"apoc\"]"
      NEO4J_AUTH: neo4j/test

    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

  app:
    image: alpine
    depends_on:
      neo4j:
        condition: service_healthy